### ISSUE TITLE
cannot be displayed normally

### ISSUE THREAD

**Issue by 17853313621** [AvivitY/EasyDish#1]
After compiling and installing it to the mobile phone, it cannot be displayed normally. What is the reason?
Looking forward to your answer, thank you！
![797b8b29c946d1244cc318e05e2760f](https://user-images.githubusercontent.com/70375521/178135968-907fe2ce-1494-4d44-8449-101b89f08570.jpg)

**Comment by AvivitY** [comment]
Does the problem occur after signing up? did you sign up using google?
